// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDao9GjNoIFUhv5odeCgWtzjvDFS1C9Rb4',
    appId: '1:632681974624:web:50aa6581619664127c6c05',
    messagingSenderId: '632681974624',
    projectId: 'workout-tracker-5b016',
    authDomain: 'workout-tracker-5b016.firebaseapp.com',
    storageBucket: 'workout-tracker-5b016.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAntGnfApX-vTqW0sHuuM85VDMcUMKOL5U',
    appId: '1:632681974624:android:825d8bb48af840537c6c05',
    messagingSenderId: '632681974624',
    projectId: 'workout-tracker-5b016',
    storageBucket: 'workout-tracker-5b016.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtzZ0dU-a9_zUUNCmuOgqReKIYcogkjQ0',
    appId: '1:632681974624:ios:9970e4fba373c3c57c6c05',
    messagingSenderId: '632681974624',
    projectId: 'workout-tracker-5b016',
    storageBucket: 'workout-tracker-5b016.firebasestorage.app',
    iosBundleId: 'com.seoyoung.workoutTracker',
  );
}
